Having grid items causes an error.
> Error: hr is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`

Will use custom css-grid for now.